import type { Metadata } from "next"
import { ReactNode } from "react"
import { inter } from "@/config/fonts"
import "./globals.css"
import { Providers } from "./providers"

export const metadata: Metadata = {
  title: "Rol App",
  description: "Generated by create next app",
}

export default function AuthLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>
          <main style={{height: "100%", minHeight: "100vh"}} >
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
